version: '3'
services:
  frontend:
    image: "simonbaudart/picshare:client-photobooth-latest"
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_BACKEND_URL=http://localhost:3001
      - PUBLIC_FRONT_URL=http://localhost:3002
  
  backend:
    image: "simonbaudart/picshare:service-photobooth-latest"
    ports:
      - "3001:80"
    depends_on:
      - redis
      - placement
    networks:
      - hello-dapr
    volumes:
      - "./pictures/:/app/pictures"
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000
      - PHOTOBOOTH_ORGANISATION=23a47be4-a501-4641-b73a-b497813b8e06
      - PHOTOBOOTH_SESSION=bb077631-61f2-4ca3-bedf-41ef6e492107
      - PHOTOBOOTH_PICTURES_SOURCE=/app/pictures
  
  backend-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "-app-id", "picshare-photobooth",
      "-app-port", "80",
      "-placement-host-address", "placement:50006",
      "--components-path", "/components",
      "--dapr-http-max-request-size", "30"
    ]
    volumes:
      - "./components/:/components"
      - "C:\\tmp\\picshare:/tmp/picshare"
    depends_on:
      - backend
    network_mode: "service:backend"
    
  live:
    image: "simonbaudart/picshare:service-photobooth-live-latest"
    ports:
      - "3002:80"
    depends_on:
      - redis
      - placement
    networks:
      - hello-dapr
    volumes:
      - "./pictures/:/app/pictures"

  live-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "-app-id", "picshare-photobooth-live",
      "-app-port", "80",
      "-placement-host-address", "placement:50006",
      "--components-path", "/components",
      "--dapr-http-max-request-size", "30"
    ]
    volumes:
      - "./components/:/components"
      - "C:\\tmp\\picshare:/tmp/picshare"
    depends_on:
      - live
    network_mode: "service:live"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - hello-dapr
  
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - hello-dapr
networks:
  hello-dapr: