name: Build and Publish Nuget
on:
  workflow_call:
    inputs:
      projectPath:
        required: true
        type: string
jobs:
  version:
    uses : ./.github/workflows/actions-utils-version.yaml
  display:
    needs: version
    steps:
      - run: echo ${{ needs.version.outputs.informationalVersion }} ${{ needs.version.outputs.assemblyVersion }}