name: Build

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/services

      - name: Build
        run: dotnet build --no-restore
        working-directory: ./src/services

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./src/services