name: CD - Nightly

on:
  push:
    branches:
      - main
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  api:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./services/Prism.Picshare.Services.Api/Dockerfile
      imageTag: service-api
      workingDirectory: src/net/
      isProduction: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
  workers:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./services/Prism.Picshare.Services.Workers/Dockerfile
      imageTag: service-workers
      workingDirectory: src/net/
      isProduction: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
  front:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./Dockerfile
      imageTag: client-front-public
      workingDirectory: src/clients/front/
      isProduction: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  reload-apps:
    runs-on: ubuntu-latest
    needs: [api, front]
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI - Update App
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update -n ${{ secrets.DEV_AZURE_APP_API }} -g ${{ secrets.DEV_AZURE_RG }} --image docker.io/simonbaudart/picshare:service-api-nightly
            az containerapp update -n ${{ secrets.DEV_AZURE_APP_FRONT }} -g ${{ secrets.DEV_AZURE_RG }} --image docker.io/simonbaudart/picshare:client-front-public-nightly
