name: CD - Nightly

on:
  push:
    branches:
      - main
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract Version
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Build
        working-directory: src/net/
        run: |
          dotnet build services/Prism.Picshare.AzureServices.Api/Prism.Picshare.AzureServices.Api.csproj --configuration Release --output ./output

      - name: Publish
        uses: Azure/functions-action@v1
        with:
          app-name: picshare-dev-api
          package: src/net/output
          publish-profile: ${{ secrets.DEV_AZURE_FUNCTIONAPP_PUBLISH_PROFILE_API }}
          
  workers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract Version
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Build
        working-directory: src/net/
        run: |
          dotnet build services/Prism.Picshare.AzureServices.Workers/Prism.Picshare.AzureServices.Workers.csproj --configuration Release --output ./output

      - name: Publish
        uses: Azure/functions-action@v1
        with:
          app-name: picshare-dev-api
          package: src/net/output
          publish-profile: ${{ secrets.DEV_AZURE_FUNCTIONAPP_PUBLISH_PROFILE_WORKERS }}
  
  front-public:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./Dockerfile
      imageTag: client-front-public
      workingDirectory: src/clients/front/
      isProduction: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
