name: CD

on:
  release:
    types: [ published ]
  workflow_dispatch:
    
jobs:
  publish-services-authentication:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./services/authentication/Prism.Picshare.Services.Authentication/Dockerfile
      imageTag: service-authentication
      workingDirectory: src/net/
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
  publish-services-mailing:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./services/mailing/Prism.Picshare.Services.Mailing/Dockerfile
      imageTag: service-mailing
      workingDirectory: src/net/
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
  publish-services-pictures:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./services/pictures/Prism.Picshare.Services.Pictures/Dockerfile
      imageTag: service-pictures
      workingDirectory: src/net/
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
  publish-clients-front-public:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./Dockerfile
      imageTag: client-front-public
      workingDirectory: src/clients/front/
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}