name: CD

on:
  release:
    types: [ published ]
  workflow_dispatch:
    
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract Version
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Build
        working-directory: src/net/
        run: |
          dotnet build services/Prism.Picshare.AzureServices.Api/Prism.Picshare.AzureServices.Api.csproj --configuration Release --output ./output

      - name: Publish
        uses: Azure/functions-action@v1
        with:
          app-name: picshare-dev-api
          package: src/net/output
          publish-profile: ${{ secrets.PRD_AZURE_FUNCTIONAPP_PUBLISH_PROFILE_API }}
  
  workers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract Version
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Build
        working-directory: src/net/
        run: |
          dotnet build services/Prism.Picshare.AzureServices.Workers/Prism.Picshare.AzureServices.Workers.csproj --configuration Release --output ./output

      - name: Publish
        uses: Azure/functions-action@v1
        with:
          app-name: picshare-dev-api
          package: src/net/output
          publish-profile: ${{ secrets.PRD_AZURE_FUNCTIONAPP_PUBLISH_PROFILE_WORKERS }}
  
  front-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Packages
        working-directory: ./src/clients/front
        run: yarn install --frozen-lockfile

      - name: Build Project
        working-directory: ./src/clients/front
        run: yarn build

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.PRD_AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          skip_app_build: true
          skip_api_build: true
          action: "upload"
          app_location: "src/clients/front/out"
