name: CD

on:
  release:
    types: [ published ]
  workflow_dispatch:
    
jobs:
  api:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./services/Prism.Picshare.Services.Api/Dockerfile
      imageTag: service-api
      workingDirectory: src/net/
      isProduction: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  workers:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./services/Prism.Picshare.Services.Workers/Dockerfile
      imageTag: service-workers
      workingDirectory: src/net/
      isProduction: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  front:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./Dockerfile
      imageTag: client-front-public
      workingDirectory: src/clients/front/
      isProduction: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}