name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-libs-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Trick for Sonar
        run: rm -f ./sonar-project.properties

      - name: Build and Analyze
        uses: highbyte/sonarscan-dotnet@v2.1.2
        with:
          sonarProjectKey: prism-be_picshare-libs-main
          sonarProjectName: Prism.Picshare
          sonarOrganization: prism-be
          dotnetBuildArguments: ./src/libs/Prism.Picshare
          dotnetTestArguments: ./src/libs/Prism.Picshare --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-services:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Trick for Sonar
        run: rm -f ./sonar-project.properties

      - name: BackEnd - Build and Analyze
        uses: highbyte/sonarscan-dotnet@v2.1.2
        with:
          sonarProjectKey: prism-be_picshare-services
          sonarProjectName: Prism.Picshare.Services
          sonarOrganization: prism-be
          dotnetBuildArguments: ./src/services
          dotnetTestArguments: ./src/services --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build-front-photobooth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.1.9

      - name: Install Packages
        working-directory: src/clients/photobooth
        run: pnpm install

      - name: Build Project
        working-directory: src/clients/photobooth
        run: pnpm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: src/clients/photobooth
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}